# Generated by Django 4.2 on 2025-10-07 22:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.CharField(choices=[('M', 'Musique'), ('S', 'Sport'), ('C', 'Cinema')], max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('nbe_participant', models.IntegerField(default=0)),
                ('evt_date', models.DateField(verbose_name="Date de l'evenement")),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Création')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date màj')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participation', models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Evenement',
                'ordering': ('title', 'evt_date'),
            },
        ),
        migrations.CreateModel(
            name='participation_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('person', 'event')},
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2025, 10, 7, 23, 25, 17, 69610))), name='Please check your event date!'),
        ),
    ]
