# Generated by Django 4.2 on 2025-10-07 22:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Participations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='participation_event',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participation_event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participation_event',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('title', 'evt_date'), 'verbose_name_plural': 'Événements'},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='Please check your event date!',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participation',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Musique', 'Musique'), ('Cinema', 'Cinéma'), ('Sport', 'Sport')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='evt_date',
            field=models.DateField(verbose_name="Date de l'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date MAJ'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2025, 10, 7, 22, 42, 1, 158367, tzinfo=datetime.timezone.utc))), name='check_event_date'),
        ),
        migrations.DeleteModel(
            name='participation_event',
        ),
        migrations.AddField(
            model_name='participation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='Event.event'),
        ),
        migrations.AddField(
            model_name='participation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('person', 'event')},
        ),
    ]
