# Generated by Django 4.2 on 2025-10-08 00:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Event', '0002_participation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='participation_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('title', 'evt_date'), 'verbose_name_plural': 'Evenement'},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='check_event_date',
        ),
        migrations.AddField(
            model_name='event',
            name='participation',
            field=models.ManyToManyField(related_name='participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('M', 'Musique'), ('S', 'Sport'), ('C', 'Cinema')], max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='evt_date',
            field=models.DateField(verbose_name="Date de l'evenement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date màj'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2025, 10, 8, 1, 8, 47, 449567))), name='Please check your event date!'),
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.AddField(
            model_name='participation_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AddField(
            model_name='participation_event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='participation_event',
            unique_together={('person', 'event')},
        ),
    ]
