# Generated by Django 4.2 on 2025-10-08 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_participation_event_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Please check your event date!',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2025, 10, 8, 1, 8, 53, 199876))), name='Please check your event date!'),
        ),
    ]
